// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD413zNcBRjvrPPh9U6N3nCqKoPyadZjVw',
    appId: '1:230628255456:web:75b0f3e3e7f3b43728d285',
    messagingSenderId: '230628255456',
    projectId: 'bi-digital-banking',
    authDomain: 'bi-digital-banking.firebaseapp.com',
    storageBucket: 'bi-digital-banking.firebasestorage.app',
    measurementId: 'G-LGSLG4JQQZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsk07b7lv78aG3vWffgzjqefFicV2rNno',
    appId: '1:230628255456:android:eea21c0fa433209728d285',
    messagingSenderId: '230628255456',
    projectId: 'bi-digital-banking',
    storageBucket: 'bi-digital-banking.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaz4fecUDxX08jRJLG3JN8gvVULiNaY48',
    appId: '1:230628255456:ios:20a7dc839e60aa4128d285',
    messagingSenderId: '230628255456',
    projectId: 'bi-digital-banking',
    storageBucket: 'bi-digital-banking.firebasestorage.app',
    iosBundleId: 'com.dennis.bankingApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaz4fecUDxX08jRJLG3JN8gvVULiNaY48',
    appId: '1:230628255456:ios:20a7dc839e60aa4128d285',
    messagingSenderId: '230628255456',
    projectId: 'bi-digital-banking',
    storageBucket: 'bi-digital-banking.firebasestorage.app',
    iosBundleId: 'com.dennis.bankingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD413zNcBRjvrPPh9U6N3nCqKoPyadZjVw',
    appId: '1:230628255456:web:1c5210875450c0b028d285',
    messagingSenderId: '230628255456',
    projectId: 'bi-digital-banking',
    authDomain: 'bi-digital-banking.firebaseapp.com',
    storageBucket: 'bi-digital-banking.firebasestorage.app',
    measurementId: 'G-5QDZF2SNJ7',
  );
}
